packages:
  - 'packages/*'

catalog:
  vue: ^3.5.13
  '@vueuse/core': ^12.4.0
  '@tauri-apps/api': ^2.0.0
  '@tauri-apps/plugin-fs': ^2.0.0
  '@tauri-apps/plugin-sql': ^2.0.0
  '@tauri-apps/plugin-store': ^2.0.0
  '@tauri-apps/plugin-upload': ^2.0.0
